[package]
name = "rpncalc"
version = "0.1.0"
authors = ["Tsukasa Horinouchi <tsukasa.horinouchi@groove-x.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
clap = "=3.0.0-beta.2"
